# Manual: Debug volumes
# https://itnext.io/debugging-kubernetes-pvcs-a150f5efbe95

kind: Pod
apiVersion: v1
metadata:
  name: volume-debugger
spec:
  volumes:
    - name: jupyter-volume
      persistentVolumeClaim:
       claimName: claim_name_goes_here
  containers:
    - name: debugger
      image: busybox
      command: ['sleep', '3600']
      volumeMounts:
        - mountPath: "/data"
          name: jupyter-volume
      resources:
        requests:
          memory: "0.1Gi"
          cpu: "0.1"
        limits:
          memory: "2Gi"
          cpu: "1"