serverFiles:
  prometheus.yml:
  scrape_configs:
  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: replace
        target_label: __scheme__
        source_labels: [__meta_kubernetes_node_annotation_prometheus_io_scheme]
      - action: replace
        target_label: __address__
        source_labels: [__address__]
        regex: (.+):10250
        replacement: ${1}:10255
      - action: replace
        target_label: __metrics_path__
        source_labels: [__meta_kubernetes_node_annotation_prometheus_io_path]
        regex: /metrics
        replacement: /metrics/cadvisor
  - job_name: 'kubernetes-metrics-server'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - kube-system
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: metrics-server;https-metrics
  - job_name: 'fastapi'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
