apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-volume
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/jupyter-volume/