# Persistance volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-volume-claim-2
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce