# apply the secret: kubectl apply -f mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data: # echo -n 'superPassword' | base64
  mongo-root-username: Ym90dGxlbmVja29wZW5lcg== # bottleneck
  mongo-root-password: c3VwZXJQYXNzd29yZA== # superPassword
